<#
.SYNOPSIS
    Build executables using ps2exe

.DESCRIPTION
    Compiles PowerShell scripts into executables using ps2exe. Takes bundled scripts
    (generated by Invoke-PsScriptBundler.ps1) as input and manages ps2exe compilation
    parameters for each target executable.

    Builds three executables:
    - Focus-Game-Deck.exe: Main router that launches sub-processes
    - ConfigEditor.exe: GUI configuration editor (bundled)
    - Invoke-FocusGameDeck.exe: Game launcher (bundled)

.PARAMETER BuildDir
    Directory containing bundled scripts to compile (default: build-tools/build)

.PARAMETER OutputDir
    Directory where compiled executables will be placed (default: build-tools/dist)

.PARAMETER ProjectRoot
    Root directory of the project

.PARAMETER Verbose
    Enable verbose output for detailed build progress

.EXAMPLE
    .\Build-Executables.ps1
    Builds all executables from bundled scripts in default locations

.EXAMPLE
    .\Build-Executables.ps1 -BuildDir "custom/build" -OutputDir "custom/dist"
    Builds executables with custom input/output directories

.NOTES
    Version: 1.0.0
    This script is part of the Focus Game Deck build system
    Responsibility: Compile executables using ps2exe (SRP)
#>

#Requires -Version 5.1

param(
    [string]$BuildDir = (Join-Path $PSScriptRoot "build"),
    [string]$OutputDir = (Join-Path $PSScriptRoot "dist"),
    [string]$ProjectRoot = (Split-Path $PSScriptRoot -Parent),
    [switch]$Verbose
)

# Import the BuildLogger at script level
. "$PSScriptRoot/utils/BuildLogger.ps1"

if ($Verbose) {
    $VerbosePreference = "Continue"
}

function Write-BuildMessage {
    param(
        [string]$Message,
        [string]$Level = "INFO"
    )

    Write-BuildLog "[$Level] $Message"
}

function Test-PS2EXE {
    try {
        $module = Get-Module -ListAvailable -Name ps2exe
        return $null -ne $module
    } catch {
        return $false
    }
}

function Build-Executable {
    param(
        [string]$InputScript,
        [string]$OutputExe,
        [string]$Title,
        [string]$Description,
        [bool]$NoConsole = $false,
        [bool]$RequireAdmin = $false,
        [bool]$STA = $false,
        [string]$IconFile = $null
    )


    # Import the BuildLogger
    . "$PSScriptRoot/utils/BuildLogger.ps1"
    if (-not (Test-Path $InputScript)) {
        Write-BuildMessage "Input script not found: $InputScript" "ERROR"
        return $false
    }

    Write-BuildMessage "Building: $(Split-Path $OutputExe -Leaf)" "INFO"
    Write-Verbose "  Input: $InputScript"
    Write-Verbose "  Output: $OutputExe"

    try {
        $ps2exeParams = @{
            inputFile = $InputScript
            outputFile = $OutputExe
            title = $Title
            description = $Description
            company = "Focus Game Deck Project"
            version = "3.0.0.0"
            copyright = "MIT License"
            requireAdmin = $RequireAdmin
            STA = $STA
            noConsole = $NoConsole
        }

        if ($IconFile -and (Test-Path $IconFile)) {
            $ps2exeParams.Add("iconFile", $IconFile)
            Write-Verbose "  Using icon: $IconFile"
        }

        ps2exe @ps2exeParams

        if (Test-Path $OutputExe) {
            $fileSize = [math]::Round((Get-Item $OutputExe).Length / 1KB, 1)
            Write-BuildMessage "Successfully built: $(Split-Path $OutputExe -Leaf) ($fileSize KB)" "SUCCESS"
            return $true
        } else {
            Write-BuildMessage "Failed to build: $(Split-Path $OutputExe -Leaf)" "ERROR"
            return $false
        }
    } catch {
        Write-BuildMessage "Build error: $($_.Exception.Message)" "ERROR"
        return $false
    }
}

try {
    Write-BuildLog "Focus Game Deck - Executable Builder"
    # Separator removed

    if (-not (Test-PS2EXE)) {
        Write-BuildMessage "ps2exe module not found. Please run Install-BuildDependencies.ps1 first." "ERROR"
        exit 1
    }

    Import-Module ps2exe -ErrorAction Stop

    if (-not (Test-Path $OutputDir)) {
        New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
        Write-Verbose "Created output directory: $OutputDir"
    }

    $iconFile = Join-Path $ProjectRoot "assets/icon.ico"
    if (-not (Test-Path $iconFile)) {
        Write-BuildMessage "Icon file not found: $iconFile" "WARNING"
        $iconFile = $null
    }

    $buildResults = @()

    Write-Host ""
    Write-BuildMessage "Building Main Router (Focus-Game-Deck.exe)..." "INFO"
    $mainScript = Join-Path $BuildDir "Main-bundled.ps1"
    if (-not (Test-Path $mainScript)) {
        $mainScript = Join-Path $ProjectRoot "src/Main.PS1"
    }
    $mainExe = Join-Path $OutputDir "Focus-Game-Deck.exe"
    $buildResults += Build-Executable `
        -InputScript $mainScript `
        -OutputExe $mainExe `
        -Title "Focus Game Deck" `
        -Description "Gaming environment optimization tool - Main Router" `
        -NoConsole $false `
        -RequireAdmin $false `
        -STA $false `
        -IconFile $iconFile

    Write-Host ""
    Write-BuildMessage "Building Config Editor (ConfigEditor.exe)..." "INFO"
    $configEditorScript = Join-Path $BuildDir "ConfigEditor-bundled.ps1"
    if (-not (Test-Path $configEditorScript)) {
        $configEditorScript = Join-Path $ProjectRoot "gui/ConfigEditor.ps1"
    }
    $configEditorExe = Join-Path $OutputDir "ConfigEditor.exe"
    $buildResults += Build-Executable `
        -InputScript $configEditorScript `
        -OutputExe $configEditorExe `
        -Title "Focus Game Deck - Configuration Editor" `
        -Description "Focus Game Deck GUI Configuration Editor" `
        -NoConsole $false `
        -RequireAdmin $false `
        -STA $true `
        -IconFile $iconFile

    if ($Verbose) {
        Write-Host ""
        Write-BuildMessage "Building Config Editor with Console (ConfigEditor-Console.exe) for debugging..." "INFO"
        $configEditorConsoleExe = Join-Path $OutputDir "ConfigEditor-Console.exe"
        $buildResults += Build-Executable `
            -InputScript $configEditorScript `
            -OutputExe $configEditorConsoleExe `
            -Title "Focus Game Deck - Configuration Editor (Console)" `
            -Description "Focus Game Deck GUI Configuration Editor with Console (for debugging)" `
            -NoConsole $false `
            -RequireAdmin $false `
            -STA $true `
            -IconFile $iconFile
    }

    Write-Host ""
    Write-BuildMessage "Building Game Launcher (Invoke-FocusGameDeck.exe)..." "INFO"
    $gameLauncherScript = Join-Path $BuildDir "Invoke-FocusGameDeck-bundled.ps1"
    if (-not (Test-Path $gameLauncherScript)) {
        $gameLauncherScript = Join-Path $ProjectRoot "src/Invoke-FocusGameDeck.ps1"
    }
    $gameLauncherExe = Join-Path $OutputDir "Invoke-FocusGameDeck.exe"
    $buildResults += Build-Executable `
        -InputScript $gameLauncherScript `
        -OutputExe $gameLauncherExe `
        -Title "Focus Game Deck - Game Launcher" `
        -Description "Focus Game Deck Game Launcher Engine" `
        -NoConsole $false `
        -RequireAdmin $false `
        -STA $false `
        -IconFile $iconFile

    Write-Host ""
    # Separator removed
    Write-BuildLog "BUILD SUMMARY"
    # Separator removed

    $successCount = ($buildResults | Where-Object { $_ -eq $true }).Count
    $totalCount = ($buildResults | Where-Object { $_ -eq $true }).Count + ($buildResults | Where-Object { $_ -eq $false }).Count

    Write-BuildLog "Successful builds: $successCount / $totalCount"

    if ($successCount -eq $totalCount) {
        Write-BuildMessage "All executables built successfully!" "SUCCESS"

        Write-Host ""
        Write-BuildLog "Built executables:"
        Get-ChildItem $OutputDir -Filter "*.exe" | ForEach-Object {
            $fileSize = [math]::Round($_.Length / 1KB, 1)
            Write-BuildLog "  $($_.Name) ($fileSize KB)"
        }

        exit 0
    } else {
        Write-BuildMessage "Some builds failed. Check errors above." "ERROR"
        exit 1
    }

} catch {
    Write-BuildMessage "Unexpected error: $($_.Exception.Message)" "ERROR"
    Write-Verbose $_.ScriptStackTrace
    exit 1
}
