<#
.SYNOPSIS
    Embed tutorial images as Base64-encoded PowerShell string variables

.DESCRIPTION
    Reads all image files from the assets/tutorial/ directory and converts them into
    Base64-encoded PowerShell string variables. The output is written to
    build-tools/build/TutorialImageResources.ps1 which can be dot-sourced by the
    tutorial system to access embedded images.

    This allows the application to run without external image file dependencies in
    production builds while maintaining the ability to load from files during development.

.PARAMETER ProjectRoot
    Root directory of the project (default: parent of build-tools)

.PARAMETER OutputPath
    Path where the generated TutorialImageResources.ps1 file will be written
    (default: build-tools/build/TutorialImageResources.ps1)

.PARAMETER Verbose
    Enable verbose output for detailed processing information

.EXAMPLE
    .\Embed-TutorialImages.ps1
    Embeds all tutorial images using default paths

.EXAMPLE
    .\Embed-TutorialImages.ps1 -Verbose
    Embeds tutorial images with detailed progress output

.NOTES
    Version: 1.0.0
    This script is part of the Focus Game Deck build system
    Responsibility: Convert tutorial image files to embedded Base64 PowerShell variables (SRP)
#>

#Requires -Version 5.1

param(
    [string]$ProjectRoot = (Split-Path $PSScriptRoot -Parent),
    [string]$OutputPath = "",
    [switch]$Verbose
)

if ($Verbose) {
    $VerbosePreference = "Continue"
}

function Write-EmbedMessage {
    param(
        [string]$Message,
        [string]$Level = "INFO"
    )

    Write-Host "[$Level] $Message"
}

function Convert-ImageToBase64Variable {
    param(
        [string]$FilePath,
        [string]$FileName
    )

    try {
        Write-Verbose "Processing image file: $FileName"

        $imageBytes = [System.IO.File]::ReadAllBytes($FilePath)
        $base64String = [Convert]::ToBase64String($imageBytes)

        if ([string]::IsNullOrWhiteSpace($base64String)) {
            Write-EmbedMessage "Image file is empty: $FileName" "WARNING"
            return $null
        }

        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($FileName)
        $baseName = $baseName -replace '[^a-zA-Z0-9_]', '_'

        # Ensure variable name doesn't start with a number
        if ($baseName -match '^[0-9]') {
            $baseName = '_' + $baseName
        }

        $variableName = "Global:TutorialImage_$baseName"

        # Use Here-String for better readability
        $variableDefinition = "`$$variableName = @'`n$base64String`n'@"

        Write-Verbose "  Variable name: $variableName"
        Write-Verbose "  Original size: $($imageBytes.Length) bytes"
        Write-Verbose "  Base64 length: $($base64String.Length) characters"

        return $variableDefinition

    } catch {
        Write-EmbedMessage "Failed to process $FileName : $($_.Exception.Message)" "ERROR"
        return $null
    }
}

try {
    Write-Host "Focus Game Deck - Tutorial Image Embedder"
    Write-Host ("=" * 60)
    Write-Host ""

    $tutorialPath = Join-Path -Path $ProjectRoot -ChildPath "assets/tutorial"

    if (-not (Test-Path $tutorialPath)) {
        Write-EmbedMessage "Tutorial assets directory not found: $tutorialPath" "ERROR"
        exit 1
    }

    if ([string]::IsNullOrWhiteSpace($OutputPath)) {
        $OutputPath = Join-Path -Path $PSScriptRoot -ChildPath "build/TutorialImageResources.ps1"
    }

    $outputDir = Split-Path -Path $OutputPath -Parent
    if (-not (Test-Path $outputDir)) {
        Write-EmbedMessage "Creating output directory: $outputDir" "INFO"
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
    }

    # Get all image files (png, jpg, jpeg, gif)
    $imageFiles = Get-ChildItem -Path $tutorialPath -File | Where-Object {
        $_.Extension -match '\.(png|jpg|jpeg|gif)$'
    } | Sort-Object Name

    if ($imageFiles.Count -eq 0) {
        Write-EmbedMessage "No image files found in: $tutorialPath" "WARNING"
        Write-EmbedMessage "Tutorial will work but images won't be displayed" "WARNING"

        # Create an empty file with a note
        $emptyContent = @(
            "# Auto-generated by Embed-TutorialImages.ps1",
            "# Generated at: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")",
            "#",
            "# No tutorial images were found in assets/tutorial/",
            "# The tutorial system will continue to work but won't display images."
        ) -join "`n"
        Set-Content -Path $OutputPath -Value $emptyContent -Encoding UTF8 -Force
        exit 0
    }

    Write-EmbedMessage "Found $($imageFiles.Count) image file(s) in assets/tutorial/" "INFO"
    Write-Host ""

    $variableDefinitions = @()
    $processedCount = 0
    $totalSize = 0

    foreach ($imageFile in $imageFiles) {
        $variableDef = Convert-ImageToBase64Variable -FilePath $imageFile.FullName -FileName $imageFile.Name

        if ($null -ne $variableDef) {
            $variableDefinitions += $variableDef
            $processedCount++
            $totalSize += $imageFile.Length
            Write-EmbedMessage "Converted: $($imageFile.Name) ($([math]::Round($imageFile.Length / 1KB, 2)) KB)" "SUCCESS"
        }
    }

    Write-Host ""
    Write-EmbedMessage "Generating output file: $OutputPath" "INFO"

    $header = @(
        "# Auto-generated by Embed-TutorialImages.ps1"
        "# DO NOT EDIT THIS FILE MANUALLY"
        "# Generated at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
        "#"
        "# This file contains embedded tutorial image resources as Base64-encoded PowerShell Here-String variables."
        "# Each image file from assets/tutorial/ directory is converted to a global variable."
        "# Variable naming convention: `$Global:TutorialImage_<FileName>"
        "#"
        "# Example: assets/tutorial/tutorial-welcome.png -> `$Global:TutorialImage_tutorial_welcome"
        "#"
        "# Total images embedded: $processedCount"
        "# Total size: $([math]::Round($totalSize / 1KB, 2)) KB"
    ) -join "`n"

    $outputContent = $header + "`n`n" + ($variableDefinitions -join "`n`n")

    Set-Content -Path $OutputPath -Value $outputContent -Encoding UTF8 -Force

    Write-Host ""
    Write-EmbedMessage "Embedded $processedCount image(s) successfully" "SUCCESS"
    Write-EmbedMessage "Total original size: $([math]::Round($totalSize / 1KB, 2)) KB" "INFO"
    Write-EmbedMessage "Output file: $OutputPath" "INFO"

    exit 0

} catch {
    Write-EmbedMessage "Unexpected error: $($_.Exception.Message)" "ERROR"
    Write-EmbedMessage $_.ScriptStackTrace "DEBUG"
    exit 1
}
