<#
.SYNOPSIS
    PowerShell script bundler for dependency resolution

.DESCRIPTION
    Reads entry-point scripts (like ConfigEditor.ps1, Main.ps1, Invoke-FocusGameDeck.ps1),
    recursively resolves all dot-sourced dependencies (e.g., . $path references to Logger.ps1,
    AppManager.ps1, etc.), and generates a single flat .ps1 file with all dependencies included.

    This eliminates the need for ps2exe's -embedFiles parameter and ensures all code is
    compiled into the final executable.

.PARAMETER EntryPoint
    Path to the entry-point PowerShell script to bundle

.PARAMETER OutputPath
    Path where the bundled script will be written

.PARAMETER ProjectRoot
    Root directory of the project (used to resolve relative paths)

.PARAMETER Verbose
    Enable verbose output for detailed bundling progress

.EXAMPLE
    .\Invoke-PsScriptBundler.ps1 -EntryPoint "gui/ConfigEditor.ps1" -OutputPath "build/ConfigEditor-bundled.ps1"
    Bundles ConfigEditor.ps1 and all its dependencies into a single file

.EXAMPLE
    .\Invoke-PsScriptBundler.ps1 -EntryPoint "src/Invoke-FocusGameDeck.ps1" -OutputPath "build/Invoke-FocusGameDeck-bundled.ps1" -ProjectRoot "C:/project"
    Bundles the game launcher with explicit project root

.NOTES
    Version: 1.0.0
    This script is part of the Focus Game Deck build system
    Responsibility: Handle PowerShell script preprocessing and bundling (SRP)
#>

#Requires -Version 5.1

param(
    [Parameter(Mandatory = $true)]
    [string]$EntryPoint,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [string]$ProjectRoot = (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent),

    [switch]$Verbose
)

if ($Verbose) {
    $VerbosePreference = "Continue"
}

function Write-BundlerMessage {
    param(
        [string]$Message,
        [string]$Level = "INFO"
    )
    Write-Host "[$Level] $Message"
}

function Resolve-DotSourcedPath {
    param(
        [string]$Line,
        [string]$CurrentScriptDir,
        [string]$ProjectRoot
    )

    if ($Line -notmatch '^\s*\.\s+(.+)') {
        return $null
    }

    $pathExpression = $Matches[1].Trim()

    $pathExpression = $pathExpression -replace '["'']', ''

    if ($pathExpression -match '\$PSScriptRoot') {
        $resolvedPath = $pathExpression -replace '\$PSScriptRoot', $CurrentScriptDir
    } elseif ($pathExpression -match '\$projectRoot') {
        $resolvedPath = $pathExpression -replace '\$projectRoot', $ProjectRoot
    } else {
        $resolvedPath = Join-Path $CurrentScriptDir $pathExpression
    }

    $resolvedPath = $resolvedPath -replace '[\\/]+', '/'
    $resolvedPath = [System.IO.Path]::GetFullPath($resolvedPath)

    return $resolvedPath
}

function Get-ScriptDependencies {
    param(
        [string]$ScriptPath,
        [string]$ProjectRoot,
        [hashtable]$ProcessedFiles = @{}
    )

    if ($ProcessedFiles.ContainsKey($ScriptPath)) {
        Write-Verbose "Already processed: $ScriptPath"
        return @()
    }

    $ProcessedFiles[$ScriptPath] = $true

    if (-not (Test-Path $ScriptPath)) {
        Write-BundlerMessage "Script not found: $ScriptPath" "WARNING"
        return @()
    }

    Write-Verbose "Processing: $ScriptPath"

    $scriptDir = Split-Path $ScriptPath -Parent
    $content = Get-Content $ScriptPath -Raw -Encoding UTF8

    $dependencies = @()

    $lines = $content -split "`r?`n"
    foreach ($line in $lines) {
        $resolvedPath = Resolve-DotSourcedPath -Line $line -CurrentScriptDir $scriptDir -ProjectRoot $ProjectRoot

        if ($resolvedPath) {
            Write-Verbose "Found dependency: $resolvedPath"
            $dependencies += $resolvedPath

            $nestedDeps = Get-ScriptDependencies -ScriptPath $resolvedPath -ProjectRoot $ProjectRoot -ProcessedFiles $ProcessedFiles
            $dependencies += $nestedDeps
        }
    }

    return $dependencies
}

function New-BundledScript {
    param(
        [string]$EntryPointPath,
        [string]$OutputPath,
        [string]$ProjectRoot
    )

    if (-not (Test-Path $EntryPointPath)) {
        Write-BundlerMessage "Entry point not found: $EntryPointPath" "ERROR"
        return $false
    }

    $processedFiles = @{}

    Write-BundlerMessage "Resolving dependencies for: $(Split-Path $EntryPointPath -Leaf)" "INFO"
    $dependencies = Get-ScriptDependencies -ScriptPath $EntryPointPath -ProjectRoot $ProjectRoot -ProcessedFiles $processedFiles

    Write-BundlerMessage "Found $($dependencies.Count) dependencies" "INFO"

    $bundledContent = @"
# ============================================================================
# BUNDLED SCRIPT - Generated by Invoke-PsScriptBundler.ps1
# Entry Point: $EntryPointPath
# Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# ============================================================================

"@

    foreach ($depPath in $dependencies) {
        if (Test-Path $depPath) {
            Write-Verbose "Bundling: $depPath"

            $depContent = Get-Content $depPath -Raw -Encoding UTF8

            $depContent = $depContent -replace '^\s*\.\s+.+$', ''

            $bundledContent += @"

# ----------------------------------------------------------------------------
# Source: $depPath
# ----------------------------------------------------------------------------
$depContent

"@
        }
    }

    $entryContent = Get-Content $EntryPointPath -Raw -Encoding UTF8
    $entryContent = $entryContent -replace '^\s*\.\s+.+$', ''

    $bundledContent += @"

# ----------------------------------------------------------------------------
# ENTRY POINT: $EntryPointPath
# ----------------------------------------------------------------------------
$entryContent
"@

    $outputDir = Split-Path $OutputPath -Parent
    if (-not (Test-Path $outputDir)) {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
    }

    $bundledContent | Set-Content -Path $OutputPath -Encoding UTF8 -Force

    Write-BundlerMessage "Bundled script created: $OutputPath" "SUCCESS"

    $fileSize = [math]::Round((Get-Item $OutputPath).Length / 1KB, 2)
    Write-Verbose "Bundled file size: $fileSize KB"

    return $true
}

try {
    Write-Host "Focus Game Deck - Script Bundler"
    Write-Host "=" * 50

    $entryPointFull = Join-Path $ProjectRoot $EntryPoint
    if (-not (Test-Path $entryPointFull)) {
        $entryPointFull = $EntryPoint
    }

    $success = New-BundledScript -EntryPointPath $entryPointFull -OutputPath $OutputPath -ProjectRoot $ProjectRoot

    Write-Host ""
    if ($success) {
        Write-BundlerMessage "Script bundling completed successfully" "SUCCESS"
        exit 0
    } else {
        Write-BundlerMessage "Script bundling failed" "ERROR"
        exit 1
    }
} catch {
    Write-BundlerMessage "Unexpected error: $($_.Exception.Message)" "ERROR"
    Write-Verbose $_.ScriptStackTrace
    exit 1
}

